### ISSUE TITLE
Can't see the architecture discussed on LinkedIn

### ISSUE THREAD

**Issue by sbatezat** [maxeema/max_clean_arch#1]
Hi,

I'm starting to learn Flutter and - as a huge fan of the clean architecture - would like to find some sample.
I've seen your article from https://www.linkedin.com/pulse/flutter-howto-clean-architecture-bloc-rxdart-max-shemetov and it seems to fit my needs. However, this repository doesn't contains the architecture coming from this article (example: folders data/domain/presentation doesn't exists inside the lib folder).

I understand that "This example app is made for educational purposes. It is subject to change, refactors, and improvements.". But :

1. Why is it not possible to see the history of your commits? This repository only contains one revision (5 days ago) and there is nothing about your previous work available. Seeing the history could help to understand what you'v done and why!
2. If this repo is an improvement since your last try, could you please explain (maybe in a new article?) what is this new architecture and why it's better than the previous one for your needs?

Anyway, thanks for this work!

**Comment by maxeema** [comment]
Hello!

Original (deprecated) version of the project is available here:
https://github.com/maxeema/max_clean_arch/tree/master/old/max_clean_arch

Kind regards,
Max

**Comment by sbatezat** [comment]
Many thanks for this answer.

Some thought about your changes:

- I agree with the idea to create dedicated module for the data and domain layers. That's make them reusable if needed, and force developers to embrace the clean architecture (no possibility to make a wrong implementation). 👍 
- However I don't understand why you don't have a domain package and a data one. Finding models inside the repository folder doesn't seems to be the right thing in a real app. Imagine you've got a user model. You will probably have to use it accross multiple repository and/or use cases (getProductOfUser, getPetOfUser, ...). What have motivated you do do these changes?
